#include "global.h"

/* ENTITY GRAPHICS */
/*********************************************************************************************/
int graphicsSpaceShip[SPACESHIP_ROWS][SPACESHIP_COLS] = {
        {COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY},
        {COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, BG_DAMAGE_1, BG_WHITE, BG_YELLOW},
        {BG_DAMAGE_2, BG_WHITE, BG_WHITE, BG_WHITE, BG_DAMAGE_1, COLOR_EMPTY},
        {BG_RED, BG_WHITE, BG_WHITE, BG_WHITE, BG_WHITE, COLOR_EMPTY},
        {COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, BG_WHITE, BG_DAMAGE_1, BG_YELLOW},
        {COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY}
};

int graphicsSpaceShipDestroyed[SPACESHIP_ROWS][SPACESHIP_COLS] = {
        {COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, BG_YELLOW},
        {BG_RED, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, BG_WHITE, COLOR_EMPTY},
        {COLOR_EMPTY, COLOR_EMPTY, BG_WHITE, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY},
        {COLOR_EMPTY, BG_WHITE, COLOR_EMPTY, BG_WHITE, BG_WHITE, COLOR_EMPTY},
        {COLOR_EMPTY, BG_WHITE, COLOR_EMPTY, BG_WHITE, COLOR_EMPTY, COLOR_EMPTY},
        {COLOR_EMPTY, BG_RED, COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY, BG_YELLOW}
};

int graphicsEnemyLvl1[ENEMY_ROWS][ENEMY_COLS] = {
        {COLOR_EMPTY, BG_RED, BG_WHITE},
        {BG_RED, BG_RED, COLOR_EMPTY},
        {COLOR_EMPTY, BG_RED, BG_WHITE}
};

int graphicsEnemyLvl2[ENEMY_ROWS][ENEMY_COLS] = {
        {BG_DAMAGE_3, COLOR_EMPTY, BG_RED},
        {COLOR_EMPTY, COLOR_EMPTY, COLOR_EMPTY},
        {BG_RED, COLOR_EMPTY, BG_RED}
};
/*********************************************************************************************/